sudo: required
dist: focal
language: generic

job:
  include:
    - arch: s390x
      env: TYPE=LXD

services:
  - docker

script:
  - arch
  - docker run -t docker:18.04-dind bash -c 'docker image list'
  - docker run --privileged -t docker:18.04-dind bash -c 'docker image list'
  - docker ps -a
