sudo: required
dist: focal
language: generic

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config

job:
  include:
    - arch: s390x
      env: TYPE=LXD

services:
  - docker

script:
  - arch
  - id
  - df -T
  - sudo cat /proc/meminfo
  - sudo cat /proc/cpuinfo
  - sysctl -n kernel.pid_max ; sysctl -n user.max_user_namespaces 
  - sudo systemctl disable apparmor
  - sudo systemctl restart docker.service
  - sudo cat /etc/docker/daemon.json
  - sudo cat /proc/self/uid_map
  - sudo systemctl status docker
  - sudo docker info
  - sudo cat /lib/systemd/system/docker.service
  - sudo apt-get update
  - sudo apt-get install wget curl conntrack git make jq
  - sudo swapoff -a
  - sudo sed -i '/ swap / s/^/#/' /etc/fstab
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.22.3/bin/linux/s390x/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.25.1/minikube-linux-s390x && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - mkdir -p $HOME/.kube $HOME/.minikube
  - touch $KUBECONFIG
  - minikube start --profile=minikube --vm-driver=none --alsologtostderr --v=2 --extra-config=kubelet.cgroup-driver=cgroupfs --extra-config=kubelet.feature-gates=KubeletInUserNamespace=true,LocalStorageCapacityIsolation=false --extra-config=apiserver.feature-gates=KubeletInUserNamespace=true,LocalStorageCapacityIsolation=false --extra-config=controller-manager.feature-gates=KubeletInUserNamespace=true,LocalStorageCapacityIsolation=false --extra-config=scheduler.feature-gates=KubeletInUserNamespace=true,LocalStorageCapacityIsolation=false --extra-config=kubeadm.ignore-preflight-errors=SystemVerification || true
  - sudo systemctl status kubelet
  - sudo journalctl -xeu kubelet
