sudo: required
dist: focal
language: generic

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config

job:
  include:
    - arch: s390x
      env: TYPE=LXD

services:
  - docker

script:
  - arch
  - id
  - sudo cat /etc/docker/daemon.json
  - docker run -t -v /var/run/docker.sock:/var/run/docker.sock docker:18.04-dind sh -c 'docker image list'
  - docker run --privileged -t -v /var/run/docker.sock:/var/run/docker.sock docker:18.04-dind sh -c 'docker image list'
  - docker ps -a
  - sudo apt-get update
  - sudo apt-get install wget curl conntrack git make
  - sudo swapoff -a
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.22.3/bin/linux/s390x/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.24.0/minikube-linux-s390x && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - mkdir -p $HOME/.kube $HOME/.minikube
  - touch $KUBECONFIG
  - docker info
  - minikube start --profile=minikube --vm-driver=docker --alsologtostderr --v=2 --extra-config=kubelet.cgroup-driver=cgroupfs --extra-config=kubeadm.ignore-preflight-errors=SystemVerification

