sudo: required
dist: focal
language: generic

job:
  include:
    - arch: amd64
      env: TYPE=VM
    - arch: s390x
      env: TYPE=LXD

services:
  - docker

script:
  - arch
  - docker run -t ubuntu:18.04 bash -c 'ls -l /'
  - docker run --privileged -t ubuntu:18.04 bash -c 'ls -l /'
  - docker ps -a
