sudo: required
dist: focal
language: generic

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config

job:
  include:
    - arch: s390x
      env: TYPE=LXD

services:
  - docker

script:
  - arch
  - id
  - df -T
  - sysctl -n kernel.pid_max ; sysctl -n user.max_user_namespaces 
  - sudo cat /etc/docker/daemon.json
  - sudo cat /proc/self/uid_map
  - sudo systemctl status docker
  - sudo cat /lib/systemd/system/docker.service
  - sudo apt-get update
  - sudo apt-get install wget curl conntrack git make jq
  - sudo swapoff -a
  - docker run -t -v /var/run/docker.sock:/var/run/docker.sock docker:18.04-dind sh -c 'docker image list'
  - docker run --privileged -t -v /var/run/docker.sock:/var/run/docker.sock docker:18.04-dind sh -c 'docker image list'
  - docker ps -a
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.22.3/bin/linux/s390x/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.25.1/minikube-linux-s390x && chmod +x minikube && sudo mv minikube /usr/local/bin/
  - mkdir -p $HOME/.kube $HOME/.minikube
  - touch $KUBECONFIG
  - docker info
  - git clone https://github.com/jonathan-albrecht-ibm/minikube && cd minikube && git switch kicbase-userns-updates-v1.25.1  && docker build -t local/kicbase:userns-updates-v1.25.1 -f ./deploy/kicbase/Dockerfile . && cd ../
  - docker image list
  - minikube start --base-image=local/kicbase:userns-updates-v1.25.1 --profile=minikube --vm-driver=docker --alsologtostderr --v=2 --extra-config=kubelet.cgroup-driver=cgroupfs --extra-config=kubelet.feature-gates=KubeletInUserNamespace=true --extra-config=kubeadm.ignore-preflight-errors=SystemVerification || true
  - docker ps -a | grep kube | grep -v pause
#  - docker logs minikube
  - docker exec minikube systemctl status docker
  - docker exec minikube cat /lib/systemd/system/docker.service
  - docker exec minikube cat /proc/self/uid_map
  - docker exec minikube cat /var/log/messages
#  - docker exec minikube systemctl status kubelet
#  - docker exec minikube journalctl -xeu kubelet
