sudo: required
dist: focal
language: generic

job:
  include:
    - arch: s390x
      env: TYPE=LXD

services:
  - docker

script:
  - arch
  - docker run -t -v /var/run/docker.sock:/var/run/docker.sock docker:18.04-dind sh -c 'docker image list'
  - docker run --privileged -t -v /var/run/docker.sock:/var/run/docker.sock docker:18.04-dind sh -c 'docker image list'
  - docker ps -a
